name: S905D KERNEL test1

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
      set_54x:
        description: "KERNEL: 5.4.x / none"
        required: false
        default: "none"
env:
  REPO_URL: https://github.com/unifreq/linux-5.4.y
  REPO_BRANCH: main
  BUILD_DIR: /tmp/kernel
  SERVERCHAN_SCKEY: true
  KVER: 5.4.y
  TOOLCHAIN: https://snapshots.linaro.org/gnu-toolchain/11.2-2021.12-1/aarch64-linux-gnu/gcc-linaro-11.2.1-2021.12-x86_64_aarch64-linux-gnu.tar.xz
  ARMBIAN_VER: Armbian_22.02.0_Aml_s905d_bullseye_5.10.100_2022.02.12.0039
jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: telegrame_bot
      run: |
        if [[ "${SERVERCHAN_SCKEY}" == "true" ]]; then
          curl -k --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "text=🎉 主人：
          您正在使用kissyouhunter仓库编译N1内核5.4.y,请耐心等待...... 😋" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
        fi

    - name: choose kernel
      run: |
        set_54x="${{ github.event.inputs.set_54x }}"
        echo "KERNEL_5_4_Y=${set_54x}" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Host info
      run: |
        pwd
        ls -lah
        lscpu
        free -h
        df -h 

    - name: Initialization environment
      env:
         DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo apt-get update
        sudo apt-get install -y build-essential crossbuild-essential-arm64 pkg-config-aarch64-linux-gnu llvm llvm-dev lld libc6-dev-arm64-cross libatomic1-arm64-cross libgcc-8-dev-arm64-cross libgcc-10-dev-arm64-cross clang qemu-user-static binfmt-support make gcc gcc-aarch64-linux-gnu gcc-10-aarch64-linux-gnu libc6-dev pkg-config netfilter-persistent xz-utils lzma rename tar openssl libidn11-dev libncurses-dev minizip bc zlibc asciidoc binutils bzip2 gawk ninja-build u-boot-tools gettext git fakeroot libncurses5-dev libz-dev patch python3 python2.7 pigz zstd zip unzip lz4 ccache zlib1g-dev btrfs-progs bison uuid uuid-dev uuid-runtime mount parted util-linux dosfstools subversion flex uglifyjs libpixman-1-dev git-core gzip p7zip p7zip-full msmtp libssl-dev vim busybox texinfo libglib2.0-dev xmlto qemu-utils qemu qemu-system qemu-user libidn11 initramfs-tools gdb-multiarch upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf wget curl swig rsync
        
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}          
        
    - name: Build Kernel  
      run: |
        mkdir -p /tmp/upload/${KERNEL_5_4_Y} && cd /tmp/upload && curl -# -LO https://github.com/kissyouhunter/kernel_N1/releases/download/armbian/linux-${KVER}.tar.gz
        curl -# -LO https://github.com/kissyouhunter/kernel_N1/releases/download/armbian/${ARMBIAN_VER}.img.gz
        gzip -d ${ARMBIAN_VER}.img.gz
        loop_armbian=$(sudo losetup -P -f --show "${ARMBIAN_VER}.img")
        sudo mount ${loop_armbian}p2 /mnt/
        sudo mount ${loop_armbian}p1 /mnt/boot/
        sudo cp /tmp/upload/linux-${KVER}.tar.gz /mnt/root/ && sudo cp $GITHUB_WORKSPACE/install_kernel.sh /mnt/root/install_kernel.sh -v
        sudo sed -i 's|n1kernel|'"$KERNEL_5_4_Y"'|g' /mnt/root/install_kernel.sh
        sudo sed -i 's|kernelnumber|'"$KVER"'|g' /mnt/root/install_kernel.sh
        cd /mnt/ && sudo chroot .
        cd root 
        chmod +x install_kernel.sh
        ./install_kernel.sh
        exit
        sudo cp /mnt/root/boot-${KERNEL_5_4_Y}-kissyouhunter.tar.gz /tmp/upload/${KERNEL_5_4_Y}
        sudo cp /mnt/root/dtb-amlogic-${KERNEL_5_4_Y}-kissyouhunter.tar.gz /tmp/upload/${KERNEL_5_4_Y}
        sudo cp /mnt/root/modules-${KERNEL_5_4_Y}-kissyouhunter.tar.gz /tmp/upload/${KERNEL_5_4_Y}
        cd /tmp/upload/ && tar -zcvf ${KERNEL_5_4_Y}.tar.gz ${KERNEL_5_4_Y}
        rm -rf ${KERNEL_5_4_Y} && rm -f ${ARMBIAN_VER}.img

    - name: Organize files
      id: organize
      run: |
        cd /tmp/upload
        rm -f ${ARMBIAN_VER}.img
        echo "KERNEL=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"

    - name: Upload kernel directory
      uses: kittaakos/upload-artifact-as-is@master
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        path: ${{ env.KERNEL }}

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 4
        
    - name: telegram_bot
      run: |
        if [[ "${SERVERCHAN_SCKEY}" == "true" ]]; then
          curl -k --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "text=我亲爱的✨主人✨：
          您使用kissyouhunter仓库编译N1内核5.4.y顺利编译完成了！💐" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
        fi
